### ISSUE TITLE
sdml:srcLabel lacks surrounding quotation in Turtle serialization

### ISSUE THREAD

**Issue by jonassmedegaard** [sdm-lang/rust-sdml#11]
Recently (between 2024-02-23 and 2024-06-28), serializing as turtle format dropped the surrounding quotation marks for sdml:srcLabel entries. This renders the output unusable.

**Comment by jonassmedegaard** [comment]
To clarify, using the concrete example you provided yourself in #9 , SDML currently produces this:
```turtle
sdml:srcLabel type_constructor_fix9 .
```

which is syntactically illegal.
The third part of that triple should be (and until recently was) a string, which needs to be quoted, like this:
```turtle
sdml:srcLabel "type_constructor_fix9" .
```

**Comment by johnstonskj** [comment]
Unfortunately the fix for #9 had this side-effect. By fixing strings that had double-quotes added above the renderer it didn't add them to strings without. This affected both `sdml:srcLabel` and `owl:VersionInfo`.

**Comment by johnstonskj** [comment]
See 377a26076e4e52ad200a567f1136d0279ce755b7

**Comment by johnstonskj** [comment]
I am in the process of bumping versions and publishing the latest versions to crates.io.

**Comment by jonassmedegaard** [comment]
Works now. Thanks a lot!
