### ISSUE TITLE
sdml-core requires rustc 1.75

### ISSUE THREAD

**Issue by jonassmedegaard** [sdm-lang/rust-sdml#8]
Compiling the code since recent refactor fc02d43 with rustc 1.70 (the version of rustc available in Debian unstable), fails like this:

```
error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in trait method return types
  --> sdml-core/src/load.rs:41:28
   |
41 |     fn resolver(&self) -> &impl ModuleResolver;
   |                            ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

For more information about this error, try `rustc --explain E0562`.
error: could not compile `sdml-core` due to previous error
```

Seemingly (according to some chatter), that syntax is supported only since rustc 1.75.

I am [currently working on packaging sdml officially for Debian](https://bugs.debian.org/1064145).
If possible, please consider rewriting that code to support rustc 1.70, as that will help getting sdml into Debian now, rather than needing to wait until Debian succeeds in upgrading its included rustc compiler.
Alternatively, if the current code is considered more beneficial (e.g. for performance reasons), then it would be helpful to me if you could suggest a patch that I could apply locally for the Debian package - I have tried and failed to wrap my head around the use of `#[async_trait]` which is mentioned at some places as a workaround.

**Comment by jonassmedegaard** [comment]
no longer needed (for Debian, at least).

**Comment by johnstonskj** [comment]
Sorry I didn't get to that.
